Disable tests for Db2
A lot of tests fail with the usual error:

```
java.lang.IllegalStateException: Needed to have 6 in buffer but only had 0
```

This is a known issue with the Vert.x driver.
See https://github.com/hibernate/hibernate-reactive/issues/1345