Skip EmptyCompositeCollectionKeyTest for Db2
Vert.x SQL client throws:
```
java.lang.IllegalStateException: Needed to have 6 in buffer but only had 0. In JDBC we would normally block here but need to find a non-blocking solution
```