[#1345] Re-enable tests for Db2
Because of issue #899 in the eclipse Vert.x SQL client, we had
often the following error:
```
java.lang.IllegalStateException: Needed to have 6 in buffer but only had 0. In JDBC we would normally block here but need to find a non-blocking solution
```

This issues has been solved in Vert.x SQL client 5.1.9:
https://github.com/eclipse-vertx/vertx-sql-client/pull/1715

Some tests are failing for different reasons now though.